#ifndef NT2_PREDICATES_FUNCTIONS_HPP_INCLUDED
#define NT2_PREDICATES_FUNCTIONS_HPP_INCLUDED

#include <nt2/predicates/include/functions/is_equal_with_equal_nans.hpp>
#include <nt2/predicates/include/functions/is_eqz.hpp>
#include <nt2/predicates/include/functions/is_even.hpp>
#include <nt2/predicates/include/functions/is_false.hpp>
#include <nt2/predicates/include/functions/is_finite.hpp>
#include <nt2/predicates/include/functions/is_flint.hpp>
#include <nt2/predicates/include/functions/is_gez.hpp>
#include <nt2/predicates/include/functions/is_gtz.hpp>
#include <nt2/predicates/include/functions/is_imag.hpp>
#include <nt2/predicates/include/functions/is_inf.hpp>
#include <nt2/predicates/include/functions/is_invalid.hpp>
#include <nt2/predicates/include/functions/is_lez.hpp>
#include <nt2/predicates/include/functions/is_ltz.hpp>
#include <nt2/predicates/include/functions/is_nan.hpp>
#include <nt2/predicates/include/functions/is_negative.hpp>
#include <nt2/predicates/include/functions/is_nez.hpp>
#include <nt2/predicates/include/functions/is_nge.hpp>
#include <nt2/predicates/include/functions/is_ngez.hpp>
#include <nt2/predicates/include/functions/is_ngt.hpp>
#include <nt2/predicates/include/functions/is_ngtz.hpp>
#include <nt2/predicates/include/functions/is_nle.hpp>
#include <nt2/predicates/include/functions/is_nlez.hpp>
#include <nt2/predicates/include/functions/is_nlt.hpp>
#include <nt2/predicates/include/functions/is_nltz.hpp>
#include <nt2/predicates/include/functions/is_not_equal_with_equal_nans.hpp>
#include <nt2/predicates/include/functions/is_not_finite.hpp>
#include <nt2/predicates/include/functions/is_not_greater.hpp>
#include <nt2/predicates/include/functions/is_not_greater_equal.hpp>
#include <nt2/predicates/include/functions/is_not_imag.hpp>
#include <nt2/predicates/include/functions/is_not_infinite.hpp>
#include <nt2/predicates/include/functions/is_not_less.hpp>
#include <nt2/predicates/include/functions/is_not_less_equal.hpp>
#include <nt2/predicates/include/functions/is_not_nan.hpp>
#include <nt2/predicates/include/functions/is_not_real.hpp>
#include <nt2/predicates/include/functions/is_odd.hpp>
#include <nt2/predicates/include/functions/is_ord.hpp>
#include <nt2/predicates/include/functions/is_positive.hpp>
#include <nt2/predicates/include/functions/is_real.hpp>
#include <nt2/predicates/include/functions/is_true.hpp>
#include <nt2/predicates/include/functions/is_unord.hpp>
#include <nt2/predicates/include/functions/majority.hpp>

#endif
