/*
 * CoreBluron, License
 * 
 * Timothee Ewart - Swiss Federal Institute of technology in Lausanne 
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef COREBLURON_O_VEC_HPP
#define COREBLURON_O_VEC_HPP

#include "numeric/math/detail/trait.hpp"
#include "numeric/math/detail/simd_wrapper.hpp"

namespace numeric{

    template<class T,memory::simd O>
    struct vec{
        typedef typename simd_trait<T,O>::value_type value_type;
        typedef typename simd_trait<T,O>::pointer pointer;
        typedef typename simd_trait<T,O>::const_pointer const_pointer;
        typedef typename simd_trait<T,O>::register_type register_type;
      
        inline explicit vec(const value_type a = value_type()){
            xmm = _mm_load1<value_type,O>(xmm,a);
        }

        inline vec(vec const& a){
            xmm = a.xmm;
        }

        inline vec(const_pointer a){
            xmm = _mm_load<value_type,O>(xmm,a);
        }

        inline vec& operator()(){
            return *this;
        }

        inline const vec& operator()() const{
            return *this;
        }

        inline vec& operator *=(const vec& rhs){
            xmm = _mm_mul<value_type,O>(xmm,rhs.xmm);
            return *this;
        }
        
        inline vec& operator /=(const vec& rhs){
            xmm = _mm_div<value_type,O>(xmm,rhs.xmm);
            return *this;
        }
        
        inline vec& operator +=(const vec& rhs){
            xmm = _mm_add<value_type,O>(xmm,rhs.xmm);
            return *this;
        }
        
        inline void store(const_pointer a) const{
            _mm_store<value_type,O>(xmm,a);
        } 

        inline void ma(const vec& lhs, const vec& rhs){
            xmm = _mm_fma<value_type,O>(xmm,lhs.xmm,rhs.xmm);
        }

        register_type xmm;
    };

    template<class T,memory::simd O>
    inline vec<T,O> operator* (const vec<T,O>& lhs, const vec<T,O>& rhs){
        vec<T,O> nrv(lhs);   // named return value optimization
        nrv *= rhs;
        return nrv;
    }

    template<class T,memory::simd O>
    inline vec<T,O> operator* (int lhs, const vec<T,O>& rhs){
        vec<T,O> nrv(lhs);
        nrv *= rhs;
        return nrv;
    }

    template<class T,memory::simd O>
    inline vec<T,O> operator/ (const vec<T,O>& lhs, const vec<T,O>& rhs){
        vec<T,O> nrv(lhs);
        nrv /= rhs;
        return nrv;
    }

    template<class T,memory::simd O>
    inline vec<T,O> operator/ (const vec<T,O>& lhs, const std::size_t rhs){
        vec<T,O> nrv(lhs);
        vec<T,O> nv_rhs(rhs);
        nrv /= nv_rhs;
        return nrv;
    }
    
    template<class T,memory::simd O>
    inline vec<T,O> operator+ (const vec<T,O>& lhs, const vec<T,O>& rhs){
        vec<T,O> nrv(lhs);
        nrv += rhs;
        return nrv;
    }

    template<class T,memory::simd O>
    inline vec<T,O> muladd(const vec<T,O>& lhs, const vec<T,O>& mhs, const vec<T,O>& rhs){
        vec<T,O> nrv(lhs);
        nrv.ma(mhs,rhs);
        return nrv;
    }



} //end namespace

#endif

