##
# @file
#
# Travis script for cyme
#
# @author Tim Ewart
#

sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake-3.4
    - gcc-4.8
    - g++-4.8
    - clang
    - libboost-all-dev
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
notifications:
  email:
    recipients:
      - timothee.ewart@gmail.com
    on_success: change
    on_failure: always
