#ifndef NT2_CORE_INCLUDE_FUNCTIONS_FUNCTION_VALUE_TYPE_HPP_INCLUDED
#define NT2_CORE_INCLUDE_FUNCTIONS_FUNCTION_VALUE_TYPE_HPP_INCLUDED

#include <nt2/core/functions/table/details/function_value_type.hpp>

#endif
