/*
 * CYME, License
 *
 * Timothee Ewart - Swiss Federal Institute of technology in Lausanne
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef CYME_REMEZ_HPP
#define CYME_REMEZ_HPP


namespace numeric{
    /** \cond */
    //just encapsulate the number of coeff
    struct coeff_remez_number{
        static const std::size_t value = 11;
    };

    // no C++ 11, so no constexpr into structure for double/float, ^.^ just partial specialization
    // These coeffs are obtained with an external program
    template<class T, std::size_t n>
    struct coeff_remez;

    template<class T>
    struct coeff_remez<T,0>{
        const static inline T coeff() {return 0.99999999999999999566016490920259318691496540598896;}
    };

    template<class T>
    struct coeff_remez<T,1>{
        const static inline T coeff() {return 1.0000000000000017952745258419615282194236357388884;}
    };

    template<class T>
    struct coeff_remez<T,2>{
        const static inline T coeff() {return 0.499999999999877094481580370323249951329122224389189;}
    };

    template<class T>
    struct coeff_remez<T,3>{
        const static inline T coeff() {return 0.166666666669960803484477734308515404418108830469798;}
    };

    template<class T>
    struct coeff_remez<T,4>{
        const static inline T coeff() {return 4.1666666621080810610346717440523105184720007971655e-2;}
    };

    template<class T>
    struct coeff_remez<T,5>{
        const static inline T coeff() {return  8.3333337052009872221152811550156335074160546333973e-3;}
    };

    template<class T>
    struct coeff_remez<T,6>{
        const static inline T coeff() {return  1.3888869684178659239014256260881685824525255547326e-3;}
    };

    template<class T>
    struct coeff_remez<T,7>{
        const static inline T coeff() {return  1.98419213985637881240770890090795533564573406893163e-4;}
    };

    template<class T>
    struct coeff_remez<T,8>{
        const static inline T coeff() {return 2.47868893393199945541176652007657202642495832996107e-5;}
    };

    template<class T>
    struct coeff_remez<T,9>{
        const static inline T coeff() {return 2.77750562801295315877005242757916081614772210463065e-6;}
    };

    template<class T>
    struct coeff_remez<T,10>{
        const static inline T coeff() {return 2.5535368519306500343384723775435166753084614063349e-7;}
    };

    template<class T>
    struct coeff_remez<T,11>{
        const static inline T coeff() {return 3.5524625185478232665958141148891055719216674475023e-8;}
    };

    /* \endcond I do not need this part in the doc*/
} //end namespace

#endif 
