#ifndef NT2_LINALG_FUNCTIONS_HPP_INCLUDED
#define NT2_LINALG_FUNCTIONS_HPP_INCLUDED

#include <nt2/linalg/include/functions/balance.hpp>
#include <nt2/linalg/include/functions/bandred.hpp>
#include <nt2/linalg/include/functions/binomial.hpp>
#include <nt2/linalg/include/functions/cauchy.hpp>
#include <nt2/linalg/include/functions/chebspec.hpp>
#include <nt2/linalg/include/functions/chebvand.hpp>
#include <nt2/linalg/include/functions/chol.hpp>
#include <nt2/linalg/include/functions/chol_solve.hpp>
#include <nt2/linalg/include/functions/chow.hpp>
#include <nt2/linalg/include/functions/circul.hpp>
#include <nt2/linalg/include/functions/clement.hpp>
#include <nt2/linalg/include/functions/compar.hpp>
#include <nt2/linalg/include/functions/cond.hpp>
#include <nt2/linalg/include/functions/condex.hpp>
#include <nt2/linalg/include/functions/cov.hpp>
#include <nt2/linalg/include/functions/cross.hpp>
#include <nt2/linalg/include/functions/cycol.hpp>
#include <nt2/linalg/include/functions/det.hpp>
#include <nt2/linalg/include/functions/dorr.hpp>
#include <nt2/linalg/include/functions/dramadah.hpp>
#include <nt2/linalg/include/functions/expm.hpp>
#include <nt2/linalg/include/functions/eyeminus.hpp>
#include <nt2/linalg/include/functions/eyeplus.hpp>
#include <nt2/linalg/include/functions/fiedler.hpp>
#include <nt2/linalg/include/functions/forsythe.hpp>
#include <nt2/linalg/include/functions/frank.hpp>
#include <nt2/linalg/include/functions/full_lu_solve.hpp>
#include <nt2/linalg/include/functions/full_qr_solve.hpp>
#include <nt2/linalg/include/functions/funm.hpp>
#include <nt2/linalg/include/functions/gcdmat.hpp>
#include <nt2/linalg/include/functions/gearmat.hpp>
#include <nt2/linalg/include/functions/geneig.hpp>
#include <nt2/linalg/include/functions/grcar.hpp>
#include <nt2/linalg/include/functions/hadamard.hpp>
#include <nt2/linalg/include/functions/hankel.hpp>
#include <nt2/linalg/include/functions/hanowa.hpp>
#include <nt2/linalg/include/functions/hilb.hpp>
#include <nt2/linalg/include/functions/house.hpp>
#include <nt2/linalg/include/functions/inv.hpp>
#include <nt2/linalg/include/functions/invhess.hpp>
#include <nt2/linalg/include/functions/invhilb.hpp>
#include <nt2/linalg/include/functions/invol.hpp>
#include <nt2/linalg/include/functions/ipjfact.hpp>
#include <nt2/linalg/include/functions/jordbloc.hpp>
#include <nt2/linalg/include/functions/kahan.hpp>
#include <nt2/linalg/include/functions/kms.hpp>
#include <nt2/linalg/include/functions/krylov.hpp>
#include <nt2/linalg/include/functions/lauchli.hpp>
#include <nt2/linalg/include/functions/ldl.hpp>
#include <nt2/linalg/include/functions/lehmer.hpp>
#include <nt2/linalg/include/functions/leslie.hpp>
#include <nt2/linalg/include/functions/lesp.hpp>
#include <nt2/linalg/include/functions/linsolve.hpp>
#include <nt2/linalg/include/functions/logm.hpp>
#include <nt2/linalg/include/functions/lotkin.hpp>
#include <nt2/linalg/include/functions/lsq_lse_solve.hpp>
#include <nt2/linalg/include/functions/lu.hpp>
#include <nt2/linalg/include/functions/magic.hpp>
#include <nt2/linalg/include/functions/minij.hpp>
#include <nt2/linalg/include/functions/minuseye.hpp>
#include <nt2/linalg/include/functions/moler.hpp>
#include <nt2/linalg/include/functions/mpower.hpp>
#include <nt2/linalg/include/functions/mtimes.hpp>
#include <nt2/linalg/include/functions/norm.hpp>
#include <nt2/linalg/include/functions/normest.hpp>
#include <nt2/linalg/include/functions/null.hpp>
#include <nt2/linalg/include/functions/options.hpp>
#include <nt2/linalg/include/functions/orth.hpp>
#include <nt2/linalg/include/functions/orthog.hpp>
#include <nt2/linalg/include/functions/parter.hpp>
#include <nt2/linalg/include/functions/pascal.hpp>
#include <nt2/linalg/include/functions/pei.hpp>
#include <nt2/linalg/include/functions/pinv.hpp>
#include <nt2/linalg/include/functions/planerot.hpp>
#include <nt2/linalg/include/functions/pluseye.hpp>
#include <nt2/linalg/include/functions/poly.hpp>
#include <nt2/linalg/include/functions/prolate.hpp>
#include <nt2/linalg/include/functions/qmult.hpp>
#include <nt2/linalg/include/functions/qr.hpp>
#include <nt2/linalg/include/functions/qrdelete.hpp>
#include <nt2/linalg/include/functions/qrinsert.hpp>
#include <nt2/linalg/include/functions/randcolu.hpp>
#include <nt2/linalg/include/functions/randcorr.hpp>
#include <nt2/linalg/include/functions/randhess.hpp>
#include <nt2/linalg/include/functions/randjorth.hpp>
#include <nt2/linalg/include/functions/rando.hpp>
#include <nt2/linalg/include/functions/randsvd.hpp>
#include <nt2/linalg/include/functions/rank.hpp>
#include <nt2/linalg/include/functions/rcond.hpp>
#include <nt2/linalg/include/functions/redheff.hpp>
#include <nt2/linalg/include/functions/riemann.hpp>
#include <nt2/linalg/include/functions/ris.hpp>
#include <nt2/linalg/include/functions/rot90.hpp>
#include <nt2/linalg/include/functions/rref.hpp>
#include <nt2/linalg/include/functions/sampling.hpp>
#include <nt2/linalg/include/functions/schur.hpp>
#include <nt2/linalg/include/functions/smoke.hpp>
#include <nt2/linalg/include/functions/sobol.hpp>
#include <nt2/linalg/include/functions/sqrtm.hpp>
#include <nt2/linalg/include/functions/subspace.hpp>
#include <nt2/linalg/include/functions/svd.hpp>
#include <nt2/linalg/include/functions/svd_solve.hpp>
#include <nt2/linalg/include/functions/symeig.hpp>
#include <nt2/linalg/include/functions/tksolve.hpp>
#include <nt2/linalg/include/functions/toeplitz.hpp>
#include <nt2/linalg/include/functions/toeppd.hpp>
#include <nt2/linalg/include/functions/toeppen.hpp>
#include <nt2/linalg/include/functions/tr_solve.hpp>
#include <nt2/linalg/include/functions/trace.hpp>
#include <nt2/linalg/include/functions/tridiag.hpp>
#include <nt2/linalg/include/functions/triw.hpp>
#include <nt2/linalg/include/functions/vandermonde.hpp>
#include <nt2/linalg/include/functions/vecnorm.hpp>

#endif
