#ifndef NT2_CORE_FUNCTIONS_HPP_INCLUDED
#define NT2_CORE_FUNCTIONS_HPP_INCLUDED

#include <nt2/core/include/functions/adjfun.hpp>
#include <nt2/core/include/functions/aggregate.hpp>
#include <nt2/core/include/functions/allbits.hpp>
#include <nt2/core/include/functions/along.hpp>
#include <nt2/core/include/functions/along_index.hpp>
#include <nt2/core/include/functions/arecatcompatible.hpp>
#include <nt2/core/include/functions/arecrosscompatible.hpp>
#include <nt2/core/include/functions/arrayfun.hpp>
#include <nt2/core/include/functions/as_size.hpp>
#include <nt2/core/include/functions/asum1.hpp>
#include <nt2/core/include/functions/asum2.hpp>
#include <nt2/core/include/functions/asump.hpp>
#include <nt2/core/include/functions/band.hpp>
#include <nt2/core/include/functions/bitincrement.hpp>
#include <nt2/core/include/functions/blkdiag.hpp>
#include <nt2/core/include/functions/bsxfun.hpp>
#include <nt2/core/include/functions/c180.hpp>
#include <nt2/core/include/functions/cast.hpp>
#include <nt2/core/include/functions/casts.hpp>
#include <nt2/core/include/functions/cat.hpp>
#include <nt2/core/include/functions/cdiff.hpp>
#include <nt2/core/include/functions/center.hpp>
#include <nt2/core/include/functions/cgold.hpp>
#include <nt2/core/include/functions/cic.hpp>
#include <nt2/core/include/functions/cif.hpp>
#include <nt2/core/include/functions/class.hpp>
#include <nt2/core/include/functions/colon.hpp>
#include <nt2/core/include/functions/cols.hpp>
#include <nt2/core/include/functions/colvect.hpp>
#include <nt2/core/include/functions/cons.hpp>
#include <nt2/core/include/functions/construct.hpp>
#include <nt2/core/include/functions/ctranspose.hpp>
#include <nt2/core/include/functions/delta.hpp>
#include <nt2/core/include/functions/deltac.hpp>
#include <nt2/core/include/functions/deltaf.hpp>
#include <nt2/core/include/functions/depth.hpp>
#include <nt2/core/include/functions/diag_of.hpp>
#include <nt2/core/include/functions/diff.hpp>
#include <nt2/core/include/functions/disp.hpp>
#include <nt2/core/include/functions/display.hpp>
#include <nt2/core/include/functions/eight.hpp>
#include <nt2/core/include/functions/eleven.hpp>
#include <nt2/core/include/functions/erase.hpp>
#include <nt2/core/include/functions/expand.hpp>
#include <nt2/core/include/functions/expand_to.hpp>
#include <nt2/core/include/functions/extent.hpp>
#include <nt2/core/include/functions/eye.hpp>
#include <nt2/core/include/functions/fact_10.hpp>
#include <nt2/core/include/functions/fact_11.hpp>
#include <nt2/core/include/functions/fact_12.hpp>
#include <nt2/core/include/functions/fact_4.hpp>
#include <nt2/core/include/functions/fact_5.hpp>
#include <nt2/core/include/functions/fact_6.hpp>
#include <nt2/core/include/functions/fact_7.hpp>
#include <nt2/core/include/functions/fact_8.hpp>
#include <nt2/core/include/functions/fact_9.hpp>
#include <nt2/core/include/functions/falses.hpp>
#include <nt2/core/include/functions/fifteen.hpp>
#include <nt2/core/include/functions/fill_pattern.hpp>
#include <nt2/core/include/functions/find.hpp>
#include <nt2/core/include/functions/findi.hpp>
#include <nt2/core/include/functions/findj.hpp>
#include <nt2/core/include/functions/first_index.hpp>
#include <nt2/core/include/functions/firstnonsingleton.hpp>
#include <nt2/core/include/functions/firstoflength.hpp>
#include <nt2/core/include/functions/five.hpp>
#include <nt2/core/include/functions/flipdim.hpp>
#include <nt2/core/include/functions/fliplr.hpp>
#include <nt2/core/include/functions/flipud.hpp>
#include <nt2/core/include/functions/four.hpp>
#include <nt2/core/include/functions/fourthrooteps.hpp>
#include <nt2/core/include/functions/freqspace.hpp>
#include <nt2/core/include/functions/freqspace1.hpp>
#include <nt2/core/include/functions/from_diag.hpp>
#include <nt2/core/include/functions/function.hpp>
#include <nt2/core/include/functions/function_index.hpp>
#include <nt2/core/include/functions/function_index_size.hpp>
#include <nt2/core/include/functions/function_index_value_type.hpp>
#include <nt2/core/include/functions/function_size.hpp>
#include <nt2/core/include/functions/function_value_type.hpp>
#include <nt2/core/include/functions/generative.hpp>
#include <nt2/core/include/functions/global.hpp>
#include <nt2/core/include/functions/globalall.hpp>
#include <nt2/core/include/functions/globalany.hpp>
#include <nt2/core/include/functions/globalasum1.hpp>
#include <nt2/core/include/functions/globalasum2.hpp>
#include <nt2/core/include/functions/globalasump.hpp>
#include <nt2/core/include/functions/globalfind.hpp>
#include <nt2/core/include/functions/globalmax.hpp>
#include <nt2/core/include/functions/globalmean.hpp>
#include <nt2/core/include/functions/globalmeanad.hpp>
#include <nt2/core/include/functions/globalmedian.hpp>
#include <nt2/core/include/functions/globalmedianad.hpp>
#include <nt2/core/include/functions/globalmin.hpp>
#include <nt2/core/include/functions/globalnone.hpp>
#include <nt2/core/include/functions/globalnorm2.hpp>
#include <nt2/core/include/functions/globalnormp.hpp>
#include <nt2/core/include/functions/globalprod.hpp>
#include <nt2/core/include/functions/globalstdev.hpp>
#include <nt2/core/include/functions/globalsum.hpp>
#include <nt2/core/include/functions/globalvar.hpp>
#include <nt2/core/include/functions/gold.hpp>
#include <nt2/core/include/functions/grids.hpp>
#include <nt2/core/include/functions/half.hpp>
#include <nt2/core/include/functions/halfeps.hpp>
#include <nt2/core/include/functions/havesamesize.hpp>
#include <nt2/core/include/functions/height.hpp>
#include <nt2/core/include/functions/homot.hpp>
#include <nt2/core/include/functions/horzcat.hpp>
#include <nt2/core/include/functions/hundred.hpp>
#include <nt2/core/include/functions/idivide.hpp>
#include <nt2/core/include/functions/ifvectvert.hpp>
#include <nt2/core/include/functions/ind2ind.hpp>
#include <nt2/core/include/functions/ind2sub.hpp>
#include <nt2/core/include/functions/indices.hpp>
#include <nt2/core/include/functions/inf.hpp>
#include <nt2/core/include/functions/inner_fold.hpp>
#include <nt2/core/include/functions/inner_scan.hpp>
#include <nt2/core/include/functions/int_splat.hpp>
#include <nt2/core/include/functions/is_definitely_vector.hpp>
#include <nt2/core/include/functions/is_vectorizable_indexer.hpp>
#include <nt2/core/include/functions/iscolumn.hpp>
#include <nt2/core/include/functions/isdiagonal.hpp>
#include <nt2/core/include/functions/isempty.hpp>
#include <nt2/core/include/functions/isequal.hpp>
#include <nt2/core/include/functions/isequaln.hpp>
#include <nt2/core/include/functions/isexpandable_to.hpp>
#include <nt2/core/include/functions/isfloating.hpp>
#include <nt2/core/include/functions/ishermitian.hpp>
#include <nt2/core/include/functions/isinside.hpp>
#include <nt2/core/include/functions/isinteger.hpp>
#include <nt2/core/include/functions/ismatrix.hpp>
#include <nt2/core/include/functions/isreal.hpp>
#include <nt2/core/include/functions/isrow.hpp>
#include <nt2/core/include/functions/isscalar.hpp>
#include <nt2/core/include/functions/issorted.hpp>
#include <nt2/core/include/functions/issquare.hpp>
#include <nt2/core/include/functions/issymetric.hpp>
#include <nt2/core/include/functions/istriangular.hpp>
#include <nt2/core/include/functions/istril.hpp>
#include <nt2/core/include/functions/istriu.hpp>
#include <nt2/core/include/functions/isulpequal.hpp>
#include <nt2/core/include/functions/isvector.hpp>
#include <nt2/core/include/functions/isvectoralong.hpp>
#include <nt2/core/include/functions/last_index.hpp>
#include <nt2/core/include/functions/ldexpmask.hpp>
#include <nt2/core/include/functions/length.hpp>
#include <nt2/core/include/functions/line.hpp>
#include <nt2/core/include/functions/linear_interp.hpp>
#include <nt2/core/include/functions/linesstride.hpp>
#include <nt2/core/include/functions/linspace.hpp>
#include <nt2/core/include/functions/log10_pi.hpp>
#include <nt2/core/include/functions/logspace.hpp>
#include <nt2/core/include/functions/make_size.hpp>
#include <nt2/core/include/functions/maxexponent.hpp>
#include <nt2/core/include/functions/maxinit.hpp>
#include <nt2/core/include/functions/maxleftshift.hpp>
#include <nt2/core/include/functions/mean.hpp>
#include <nt2/core/include/functions/meanad.hpp>
#include <nt2/core/include/functions/median.hpp>
#include <nt2/core/include/functions/medianad.hpp>
#include <nt2/core/include/functions/meight.hpp>
#include <nt2/core/include/functions/meshgrid.hpp>
#include <nt2/core/include/functions/mfive.hpp>
#include <nt2/core/include/functions/mfour.hpp>
#include <nt2/core/include/functions/mhalf.hpp>
#include <nt2/core/include/functions/mindenormal.hpp>
#include <nt2/core/include/functions/minexponent.hpp>
#include <nt2/core/include/functions/minf.hpp>
#include <nt2/core/include/functions/mlogeps2.hpp>
#include <nt2/core/include/functions/mnine.hpp>
#include <nt2/core/include/functions/mone.hpp>
#include <nt2/core/include/functions/moneo_6.hpp>
#include <nt2/core/include/functions/mseven.hpp>
#include <nt2/core/include/functions/msix.hpp>
#include <nt2/core/include/functions/mten.hpp>
#include <nt2/core/include/functions/mthree.hpp>
#include <nt2/core/include/functions/mtwo.hpp>
#include <nt2/core/include/functions/mzero.hpp>
#include <nt2/core/include/functions/nan.hpp>
#include <nt2/core/include/functions/nanasum2.hpp>
#include <nt2/core/include/functions/nanmean.hpp>
#include <nt2/core/include/functions/nansum.hpp>
#include <nt2/core/include/functions/nbdigits.hpp>
#include <nt2/core/include/functions/nbexponentbits.hpp>
#include <nt2/core/include/functions/nblines.hpp>
#include <nt2/core/include/functions/nbmantissabits.hpp>
#include <nt2/core/include/functions/ndgrid.hpp>
#include <nt2/core/include/functions/ndims.hpp>
#include <nt2/core/include/functions/nine.hpp>
#include <nt2/core/include/functions/norm2.hpp>
#include <nt2/core/include/functions/normp.hpp>
#include <nt2/core/include/functions/numel.hpp>
#include <nt2/core/include/functions/of_size.hpp>
#include <nt2/core/include/functions/ofsameheight.hpp>
#include <nt2/core/include/functions/ofsamewidth.hpp>
#include <nt2/core/include/functions/oneo_10.hpp>
#include <nt2/core/include/functions/oneo_12.hpp>
#include <nt2/core/include/functions/oneo_120.hpp>
#include <nt2/core/include/functions/oneo_15.hpp>
#include <nt2/core/include/functions/oneo_180.hpp>
#include <nt2/core/include/functions/oneo_5.hpp>
#include <nt2/core/include/functions/oneo_6.hpp>
#include <nt2/core/include/functions/oneo_7.hpp>
#include <nt2/core/include/functions/oneo_8.hpp>
#include <nt2/core/include/functions/oneo_9.hpp>
#include <nt2/core/include/functions/ones.hpp>
#include <nt2/core/include/functions/outer_fold.hpp>
#include <nt2/core/include/functions/outer_scan.hpp>
#include <nt2/core/include/functions/pi.hpp>
#include <nt2/core/include/functions/pio_2.hpp>
#include <nt2/core/include/functions/pispace.hpp>
#include <nt2/core/include/functions/putalong.hpp>
#include <nt2/core/include/functions/quarter.hpp>
#include <nt2/core/include/functions/rand.hpp>
#include <nt2/core/include/functions/randi.hpp>
#include <nt2/core/include/functions/randn.hpp>
#include <nt2/core/include/functions/real_splat.hpp>
#include <nt2/core/include/functions/reindex.hpp>
#include <nt2/core/include/functions/relative_index.hpp>
#include <nt2/core/include/functions/relative_size.hpp>
#include <nt2/core/include/functions/rephorz.hpp>
#include <nt2/core/include/functions/repmat.hpp>
#include <nt2/core/include/functions/repnum.hpp>
#include <nt2/core/include/functions/repvert.hpp>
#include <nt2/core/include/functions/reshape.hpp>
#include <nt2/core/include/functions/resize.hpp>
#include <nt2/core/include/functions/ric.hpp>
#include <nt2/core/include/functions/rif.hpp>
#include <nt2/core/include/functions/rng.hpp>
#include <nt2/core/include/functions/rows.hpp>
#include <nt2/core/include/functions/rowvect.hpp>
#include <nt2/core/include/functions/seven.hpp>
#include <nt2/core/include/functions/signmask.hpp>
#include <nt2/core/include/functions/six.hpp>
#include <nt2/core/include/functions/size.hpp>
#include <nt2/core/include/functions/smallestposval.hpp>
#include <nt2/core/include/functions/splitfactor.hpp>
#include <nt2/core/include/functions/sqrt_1o_5.hpp>
#include <nt2/core/include/functions/sqrt_2.hpp>
#include <nt2/core/include/functions/sqrt_2o_2.hpp>
#include <nt2/core/include/functions/sqrt_2o_3.hpp>
#include <nt2/core/include/functions/sqrteps.hpp>
#include <nt2/core/include/functions/sqrtsmallestposval.hpp>
#include <nt2/core/include/functions/sqrtvalmax.hpp>
#include <nt2/core/include/functions/squeeze.hpp>
#include <nt2/core/include/functions/stdev.hpp>
#include <nt2/core/include/functions/sub2ind.hpp>
#include <nt2/core/include/functions/sub2sub.hpp>
#include <nt2/core/include/functions/sx.hpp>
#include <nt2/core/include/functions/sxfun.hpp>
#include <nt2/core/include/functions/ten.hpp>
#include <nt2/core/include/functions/third.hpp>
#include <nt2/core/include/functions/thirdrooteps.hpp>
#include <nt2/core/include/functions/thousand.hpp>
#include <nt2/core/include/functions/three.hpp>
#include <nt2/core/include/functions/threeeps.hpp>
#include <nt2/core/include/functions/tie.hpp>
#include <nt2/core/include/functions/transform.hpp>
#include <nt2/core/include/functions/transpose.hpp>
#include <nt2/core/include/functions/trapz.hpp>
#include <nt2/core/include/functions/tri1l.hpp>
#include <nt2/core/include/functions/tri1u.hpp>
#include <nt2/core/include/functions/tril.hpp>
#include <nt2/core/include/functions/triu.hpp>
#include <nt2/core/include/functions/trues.hpp>
#include <nt2/core/include/functions/tsxfun.hpp>
#include <nt2/core/include/functions/twelve.hpp>
#include <nt2/core/include/functions/twenty.hpp>
#include <nt2/core/include/functions/two.hpp>
#include <nt2/core/include/functions/twoto31.hpp>
#include <nt2/core/include/functions/twotom10.hpp>
#include <nt2/core/include/functions/twotonmb.hpp>
#include <nt2/core/include/functions/valmax.hpp>
#include <nt2/core/include/functions/valmin.hpp>
#include <nt2/core/include/functions/var.hpp>
#include <nt2/core/include/functions/vertcat.hpp>
#include <nt2/core/include/functions/whereij.hpp>
#include <nt2/core/include/functions/width.hpp>
#include <nt2/core/include/functions/wmean.hpp>
#include <nt2/core/include/functions/zeros.hpp>
#include <nt2/core/include/functions/scalar/adjfun.hpp>
#include <nt2/core/include/functions/scalar/aggregate.hpp>
#include <nt2/core/include/functions/scalar/allbits.hpp>
#include <nt2/core/include/functions/scalar/along.hpp>
#include <nt2/core/include/functions/scalar/along_index.hpp>
#include <nt2/core/include/functions/scalar/arecatcompatible.hpp>
#include <nt2/core/include/functions/scalar/arecrosscompatible.hpp>
#include <nt2/core/include/functions/scalar/arrayfun.hpp>
#include <nt2/core/include/functions/scalar/as_size.hpp>
#include <nt2/core/include/functions/scalar/asum1.hpp>
#include <nt2/core/include/functions/scalar/asum2.hpp>
#include <nt2/core/include/functions/scalar/asump.hpp>
#include <nt2/core/include/functions/scalar/band.hpp>
#include <nt2/core/include/functions/scalar/bitincrement.hpp>
#include <nt2/core/include/functions/scalar/blkdiag.hpp>
#include <nt2/core/include/functions/scalar/c180.hpp>
#include <nt2/core/include/functions/scalar/cast.hpp>
#include <nt2/core/include/functions/scalar/casts.hpp>
#include <nt2/core/include/functions/scalar/cat.hpp>
#include <nt2/core/include/functions/scalar/cdiff.hpp>
#include <nt2/core/include/functions/scalar/center.hpp>
#include <nt2/core/include/functions/scalar/cgold.hpp>
#include <nt2/core/include/functions/scalar/cic.hpp>
#include <nt2/core/include/functions/scalar/cif.hpp>
#include <nt2/core/include/functions/scalar/class.hpp>
#include <nt2/core/include/functions/scalar/colon.hpp>
#include <nt2/core/include/functions/scalar/cols.hpp>
#include <nt2/core/include/functions/scalar/colvect.hpp>
#include <nt2/core/include/functions/scalar/cons.hpp>
#include <nt2/core/include/functions/scalar/construct.hpp>
#include <nt2/core/include/functions/scalar/ctranspose.hpp>
#include <nt2/core/include/functions/scalar/deltac.hpp>
#include <nt2/core/include/functions/scalar/deltaf.hpp>
#include <nt2/core/include/functions/scalar/depth.hpp>
#include <nt2/core/include/functions/scalar/diag_of.hpp>
#include <nt2/core/include/functions/scalar/diff.hpp>
#include <nt2/core/include/functions/scalar/disp.hpp>
#include <nt2/core/include/functions/scalar/display.hpp>
#include <nt2/core/include/functions/scalar/eight.hpp>
#include <nt2/core/include/functions/scalar/eleven.hpp>
#include <nt2/core/include/functions/scalar/erase.hpp>
#include <nt2/core/include/functions/scalar/expand.hpp>
#include <nt2/core/include/functions/scalar/expand_to.hpp>
#include <nt2/core/include/functions/scalar/extent.hpp>
#include <nt2/core/include/functions/scalar/eye.hpp>
#include <nt2/core/include/functions/scalar/fact_10.hpp>
#include <nt2/core/include/functions/scalar/fact_11.hpp>
#include <nt2/core/include/functions/scalar/fact_12.hpp>
#include <nt2/core/include/functions/scalar/fact_4.hpp>
#include <nt2/core/include/functions/scalar/fact_5.hpp>
#include <nt2/core/include/functions/scalar/fact_6.hpp>
#include <nt2/core/include/functions/scalar/fact_7.hpp>
#include <nt2/core/include/functions/scalar/fact_8.hpp>
#include <nt2/core/include/functions/scalar/fact_9.hpp>
#include <nt2/core/include/functions/scalar/falses.hpp>
#include <nt2/core/include/functions/scalar/fifteen.hpp>
#include <nt2/core/include/functions/scalar/fill_pattern.hpp>
#include <nt2/core/include/functions/scalar/find.hpp>
#include <nt2/core/include/functions/scalar/findi.hpp>
#include <nt2/core/include/functions/scalar/findj.hpp>
#include <nt2/core/include/functions/scalar/first_index.hpp>
#include <nt2/core/include/functions/scalar/firstnonsingleton.hpp>
#include <nt2/core/include/functions/scalar/firstoflength.hpp>
#include <nt2/core/include/functions/scalar/five.hpp>
#include <nt2/core/include/functions/scalar/flipdim.hpp>
#include <nt2/core/include/functions/scalar/fliplr.hpp>
#include <nt2/core/include/functions/scalar/flipud.hpp>
#include <nt2/core/include/functions/scalar/four.hpp>
#include <nt2/core/include/functions/scalar/fourthrooteps.hpp>
#include <nt2/core/include/functions/scalar/freqspace.hpp>
#include <nt2/core/include/functions/scalar/freqspace1.hpp>
#include <nt2/core/include/functions/scalar/from_diag.hpp>
#include <nt2/core/include/functions/scalar/function.hpp>
#include <nt2/core/include/functions/scalar/function_index.hpp>
#include <nt2/core/include/functions/scalar/global.hpp>
#include <nt2/core/include/functions/scalar/globalall.hpp>
#include <nt2/core/include/functions/scalar/globalany.hpp>
#include <nt2/core/include/functions/scalar/globalasum1.hpp>
#include <nt2/core/include/functions/scalar/globalasum2.hpp>
#include <nt2/core/include/functions/scalar/globalasump.hpp>
#include <nt2/core/include/functions/scalar/globalfind.hpp>
#include <nt2/core/include/functions/scalar/globalmax.hpp>
#include <nt2/core/include/functions/scalar/globalmean.hpp>
#include <nt2/core/include/functions/scalar/globalmeanad.hpp>
#include <nt2/core/include/functions/scalar/globalmedian.hpp>
#include <nt2/core/include/functions/scalar/globalmedianad.hpp>
#include <nt2/core/include/functions/scalar/globalmin.hpp>
#include <nt2/core/include/functions/scalar/globalnone.hpp>
#include <nt2/core/include/functions/scalar/globalnorm2.hpp>
#include <nt2/core/include/functions/scalar/globalnormp.hpp>
#include <nt2/core/include/functions/scalar/globalprod.hpp>
#include <nt2/core/include/functions/scalar/globalstdev.hpp>
#include <nt2/core/include/functions/scalar/globalsum.hpp>
#include <nt2/core/include/functions/scalar/globalvar.hpp>
#include <nt2/core/include/functions/scalar/gold.hpp>
#include <nt2/core/include/functions/scalar/half.hpp>
#include <nt2/core/include/functions/scalar/halfeps.hpp>
#include <nt2/core/include/functions/scalar/havesamesize.hpp>
#include <nt2/core/include/functions/scalar/height.hpp>
#include <nt2/core/include/functions/scalar/homot.hpp>
#include <nt2/core/include/functions/scalar/horzcat.hpp>
#include <nt2/core/include/functions/scalar/hundred.hpp>
#include <nt2/core/include/functions/scalar/idivide.hpp>
#include <nt2/core/include/functions/scalar/ifvectvert.hpp>
#include <nt2/core/include/functions/scalar/ind2ind.hpp>
#include <nt2/core/include/functions/scalar/ind2sub.hpp>
#include <nt2/core/include/functions/scalar/indices.hpp>
#include <nt2/core/include/functions/scalar/inf.hpp>
#include <nt2/core/include/functions/scalar/inner_fold.hpp>
#include <nt2/core/include/functions/scalar/inner_scan.hpp>
#include <nt2/core/include/functions/scalar/int_splat.hpp>
#include <nt2/core/include/functions/scalar/iscolumn.hpp>
#include <nt2/core/include/functions/scalar/isdiagonal.hpp>
#include <nt2/core/include/functions/scalar/isempty.hpp>
#include <nt2/core/include/functions/scalar/isequal.hpp>
#include <nt2/core/include/functions/scalar/isequaln.hpp>
#include <nt2/core/include/functions/scalar/isexpandable_to.hpp>
#include <nt2/core/include/functions/scalar/isfloating.hpp>
#include <nt2/core/include/functions/scalar/ishermitian.hpp>
#include <nt2/core/include/functions/scalar/isinside.hpp>
#include <nt2/core/include/functions/scalar/isinteger.hpp>
#include <nt2/core/include/functions/scalar/ismatrix.hpp>
#include <nt2/core/include/functions/scalar/isreal.hpp>
#include <nt2/core/include/functions/scalar/isrow.hpp>
#include <nt2/core/include/functions/scalar/isscalar.hpp>
#include <nt2/core/include/functions/scalar/issorted.hpp>
#include <nt2/core/include/functions/scalar/issquare.hpp>
#include <nt2/core/include/functions/scalar/issymetric.hpp>
#include <nt2/core/include/functions/scalar/istriangular.hpp>
#include <nt2/core/include/functions/scalar/istril.hpp>
#include <nt2/core/include/functions/scalar/istriu.hpp>
#include <nt2/core/include/functions/scalar/isulpequal.hpp>
#include <nt2/core/include/functions/scalar/isvector.hpp>
#include <nt2/core/include/functions/scalar/isvectoralong.hpp>
#include <nt2/core/include/functions/scalar/last_index.hpp>
#include <nt2/core/include/functions/scalar/ldexpmask.hpp>
#include <nt2/core/include/functions/scalar/length.hpp>
#include <nt2/core/include/functions/scalar/line.hpp>
#include <nt2/core/include/functions/scalar/linear_interp.hpp>
#include <nt2/core/include/functions/scalar/linesstride.hpp>
#include <nt2/core/include/functions/scalar/linspace.hpp>
#include <nt2/core/include/functions/scalar/log10_pi.hpp>
#include <nt2/core/include/functions/scalar/logspace.hpp>
#include <nt2/core/include/functions/scalar/maxexponent.hpp>
#include <nt2/core/include/functions/scalar/maxinit.hpp>
#include <nt2/core/include/functions/scalar/maxleftshift.hpp>
#include <nt2/core/include/functions/scalar/mean.hpp>
#include <nt2/core/include/functions/scalar/meanad.hpp>
#include <nt2/core/include/functions/scalar/median.hpp>
#include <nt2/core/include/functions/scalar/medianad.hpp>
#include <nt2/core/include/functions/scalar/meight.hpp>
#include <nt2/core/include/functions/scalar/meshgrid.hpp>
#include <nt2/core/include/functions/scalar/mfive.hpp>
#include <nt2/core/include/functions/scalar/mfour.hpp>
#include <nt2/core/include/functions/scalar/mhalf.hpp>
#include <nt2/core/include/functions/scalar/mindenormal.hpp>
#include <nt2/core/include/functions/scalar/minexponent.hpp>
#include <nt2/core/include/functions/scalar/minf.hpp>
#include <nt2/core/include/functions/scalar/mlogeps2.hpp>
#include <nt2/core/include/functions/scalar/mnine.hpp>
#include <nt2/core/include/functions/scalar/mone.hpp>
#include <nt2/core/include/functions/scalar/moneo_6.hpp>
#include <nt2/core/include/functions/scalar/mseven.hpp>
#include <nt2/core/include/functions/scalar/msix.hpp>
#include <nt2/core/include/functions/scalar/mten.hpp>
#include <nt2/core/include/functions/scalar/mthree.hpp>
#include <nt2/core/include/functions/scalar/mtwo.hpp>
#include <nt2/core/include/functions/scalar/mzero.hpp>
#include <nt2/core/include/functions/scalar/nan.hpp>
#include <nt2/core/include/functions/scalar/nanasum2.hpp>
#include <nt2/core/include/functions/scalar/nanmean.hpp>
#include <nt2/core/include/functions/scalar/nansum.hpp>
#include <nt2/core/include/functions/scalar/nbdigits.hpp>
#include <nt2/core/include/functions/scalar/nbexponentbits.hpp>
#include <nt2/core/include/functions/scalar/nblines.hpp>
#include <nt2/core/include/functions/scalar/nbmantissabits.hpp>
#include <nt2/core/include/functions/scalar/ndgrid.hpp>
#include <nt2/core/include/functions/scalar/ndims.hpp>
#include <nt2/core/include/functions/scalar/nine.hpp>
#include <nt2/core/include/functions/scalar/norm2.hpp>
#include <nt2/core/include/functions/scalar/normp.hpp>
#include <nt2/core/include/functions/scalar/numel.hpp>
#include <nt2/core/include/functions/scalar/of_size.hpp>
#include <nt2/core/include/functions/scalar/ofsameheight.hpp>
#include <nt2/core/include/functions/scalar/ofsamewidth.hpp>
#include <nt2/core/include/functions/scalar/oneo_10.hpp>
#include <nt2/core/include/functions/scalar/oneo_12.hpp>
#include <nt2/core/include/functions/scalar/oneo_120.hpp>
#include <nt2/core/include/functions/scalar/oneo_15.hpp>
#include <nt2/core/include/functions/scalar/oneo_180.hpp>
#include <nt2/core/include/functions/scalar/oneo_5.hpp>
#include <nt2/core/include/functions/scalar/oneo_6.hpp>
#include <nt2/core/include/functions/scalar/oneo_7.hpp>
#include <nt2/core/include/functions/scalar/oneo_8.hpp>
#include <nt2/core/include/functions/scalar/oneo_9.hpp>
#include <nt2/core/include/functions/scalar/ones.hpp>
#include <nt2/core/include/functions/scalar/outer_fold.hpp>
#include <nt2/core/include/functions/scalar/outer_scan.hpp>
#include <nt2/core/include/functions/scalar/pi.hpp>
#include <nt2/core/include/functions/scalar/pio_2.hpp>
#include <nt2/core/include/functions/scalar/pispace.hpp>
#include <nt2/core/include/functions/scalar/putalong.hpp>
#include <nt2/core/include/functions/scalar/quarter.hpp>
#include <nt2/core/include/functions/scalar/rand.hpp>
#include <nt2/core/include/functions/scalar/randi.hpp>
#include <nt2/core/include/functions/scalar/randn.hpp>
#include <nt2/core/include/functions/scalar/real_splat.hpp>
#include <nt2/core/include/functions/scalar/relative_index.hpp>
#include <nt2/core/include/functions/scalar/relative_size.hpp>
#include <nt2/core/include/functions/scalar/rephorz.hpp>
#include <nt2/core/include/functions/scalar/repmat.hpp>
#include <nt2/core/include/functions/scalar/repnum.hpp>
#include <nt2/core/include/functions/scalar/repvert.hpp>
#include <nt2/core/include/functions/scalar/reshape.hpp>
#include <nt2/core/include/functions/scalar/resize.hpp>
#include <nt2/core/include/functions/scalar/ric.hpp>
#include <nt2/core/include/functions/scalar/rif.hpp>
#include <nt2/core/include/functions/scalar/rng.hpp>
#include <nt2/core/include/functions/scalar/rows.hpp>
#include <nt2/core/include/functions/scalar/rowvect.hpp>
#include <nt2/core/include/functions/scalar/seven.hpp>
#include <nt2/core/include/functions/scalar/signmask.hpp>
#include <nt2/core/include/functions/scalar/six.hpp>
#include <nt2/core/include/functions/scalar/size.hpp>
#include <nt2/core/include/functions/scalar/smallestposval.hpp>
#include <nt2/core/include/functions/scalar/splitfactor.hpp>
#include <nt2/core/include/functions/scalar/sqrt_1o_5.hpp>
#include <nt2/core/include/functions/scalar/sqrt_2.hpp>
#include <nt2/core/include/functions/scalar/sqrt_2o_2.hpp>
#include <nt2/core/include/functions/scalar/sqrt_2o_3.hpp>
#include <nt2/core/include/functions/scalar/sqrteps.hpp>
#include <nt2/core/include/functions/scalar/sqrtsmallestposval.hpp>
#include <nt2/core/include/functions/scalar/sqrtvalmax.hpp>
#include <nt2/core/include/functions/scalar/squeeze.hpp>
#include <nt2/core/include/functions/scalar/stdev.hpp>
#include <nt2/core/include/functions/scalar/sub2ind.hpp>
#include <nt2/core/include/functions/scalar/sub2sub.hpp>
#include <nt2/core/include/functions/scalar/sx.hpp>
#include <nt2/core/include/functions/scalar/sxfun.hpp>
#include <nt2/core/include/functions/scalar/ten.hpp>
#include <nt2/core/include/functions/scalar/third.hpp>
#include <nt2/core/include/functions/scalar/thirdrooteps.hpp>
#include <nt2/core/include/functions/scalar/thousand.hpp>
#include <nt2/core/include/functions/scalar/three.hpp>
#include <nt2/core/include/functions/scalar/threeeps.hpp>
#include <nt2/core/include/functions/scalar/tie.hpp>
#include <nt2/core/include/functions/scalar/transform.hpp>
#include <nt2/core/include/functions/scalar/transpose.hpp>
#include <nt2/core/include/functions/scalar/trapz.hpp>
#include <nt2/core/include/functions/scalar/tri1l.hpp>
#include <nt2/core/include/functions/scalar/tri1u.hpp>
#include <nt2/core/include/functions/scalar/tril.hpp>
#include <nt2/core/include/functions/scalar/triu.hpp>
#include <nt2/core/include/functions/scalar/trues.hpp>
#include <nt2/core/include/functions/scalar/twelve.hpp>
#include <nt2/core/include/functions/scalar/twenty.hpp>
#include <nt2/core/include/functions/scalar/two.hpp>
#include <nt2/core/include/functions/scalar/twoto31.hpp>
#include <nt2/core/include/functions/scalar/twotom10.hpp>
#include <nt2/core/include/functions/scalar/twotonmb.hpp>
#include <nt2/core/include/functions/scalar/valmax.hpp>
#include <nt2/core/include/functions/scalar/valmin.hpp>
#include <nt2/core/include/functions/scalar/var.hpp>
#include <nt2/core/include/functions/scalar/vertcat.hpp>
#include <nt2/core/include/functions/scalar/whereij.hpp>
#include <nt2/core/include/functions/scalar/width.hpp>
#include <nt2/core/include/functions/scalar/wmean.hpp>
#include <nt2/core/include/functions/scalar/zeros.hpp>
#include <nt2/core/include/functions/simd/adjfun.hpp>
#include <nt2/core/include/functions/simd/aggregate.hpp>
#include <nt2/core/include/functions/simd/allbits.hpp>
#include <nt2/core/include/functions/simd/along.hpp>
#include <nt2/core/include/functions/simd/along_index.hpp>
#include <nt2/core/include/functions/simd/arecatcompatible.hpp>
#include <nt2/core/include/functions/simd/arecrosscompatible.hpp>
#include <nt2/core/include/functions/simd/arrayfun.hpp>
#include <nt2/core/include/functions/simd/as_size.hpp>
#include <nt2/core/include/functions/simd/asum1.hpp>
#include <nt2/core/include/functions/simd/asum2.hpp>
#include <nt2/core/include/functions/simd/asump.hpp>
#include <nt2/core/include/functions/simd/band.hpp>
#include <nt2/core/include/functions/simd/bitincrement.hpp>
#include <nt2/core/include/functions/simd/blkdiag.hpp>
#include <nt2/core/include/functions/simd/c180.hpp>
#include <nt2/core/include/functions/simd/cast.hpp>
#include <nt2/core/include/functions/simd/casts.hpp>
#include <nt2/core/include/functions/simd/cat.hpp>
#include <nt2/core/include/functions/simd/cdiff.hpp>
#include <nt2/core/include/functions/simd/center.hpp>
#include <nt2/core/include/functions/simd/cgold.hpp>
#include <nt2/core/include/functions/simd/cic.hpp>
#include <nt2/core/include/functions/simd/cif.hpp>
#include <nt2/core/include/functions/simd/class.hpp>
#include <nt2/core/include/functions/simd/colon.hpp>
#include <nt2/core/include/functions/simd/cols.hpp>
#include <nt2/core/include/functions/simd/colvect.hpp>
#include <nt2/core/include/functions/simd/cons.hpp>
#include <nt2/core/include/functions/simd/construct.hpp>
#include <nt2/core/include/functions/simd/ctranspose.hpp>
#include <nt2/core/include/functions/simd/deltac.hpp>
#include <nt2/core/include/functions/simd/deltaf.hpp>
#include <nt2/core/include/functions/simd/depth.hpp>
#include <nt2/core/include/functions/simd/diag_of.hpp>
#include <nt2/core/include/functions/simd/diff.hpp>
#include <nt2/core/include/functions/simd/disp.hpp>
#include <nt2/core/include/functions/simd/display.hpp>
#include <nt2/core/include/functions/simd/eight.hpp>
#include <nt2/core/include/functions/simd/eleven.hpp>
#include <nt2/core/include/functions/simd/erase.hpp>
#include <nt2/core/include/functions/simd/expand.hpp>
#include <nt2/core/include/functions/simd/expand_to.hpp>
#include <nt2/core/include/functions/simd/extent.hpp>
#include <nt2/core/include/functions/simd/eye.hpp>
#include <nt2/core/include/functions/simd/fact_10.hpp>
#include <nt2/core/include/functions/simd/fact_11.hpp>
#include <nt2/core/include/functions/simd/fact_12.hpp>
#include <nt2/core/include/functions/simd/fact_4.hpp>
#include <nt2/core/include/functions/simd/fact_5.hpp>
#include <nt2/core/include/functions/simd/fact_6.hpp>
#include <nt2/core/include/functions/simd/fact_7.hpp>
#include <nt2/core/include/functions/simd/fact_8.hpp>
#include <nt2/core/include/functions/simd/fact_9.hpp>
#include <nt2/core/include/functions/simd/falses.hpp>
#include <nt2/core/include/functions/simd/fifteen.hpp>
#include <nt2/core/include/functions/simd/fill_pattern.hpp>
#include <nt2/core/include/functions/simd/find.hpp>
#include <nt2/core/include/functions/simd/findi.hpp>
#include <nt2/core/include/functions/simd/findj.hpp>
#include <nt2/core/include/functions/simd/first_index.hpp>
#include <nt2/core/include/functions/simd/firstnonsingleton.hpp>
#include <nt2/core/include/functions/simd/firstoflength.hpp>
#include <nt2/core/include/functions/simd/five.hpp>
#include <nt2/core/include/functions/simd/flipdim.hpp>
#include <nt2/core/include/functions/simd/fliplr.hpp>
#include <nt2/core/include/functions/simd/flipud.hpp>
#include <nt2/core/include/functions/simd/four.hpp>
#include <nt2/core/include/functions/simd/fourthrooteps.hpp>
#include <nt2/core/include/functions/simd/freqspace.hpp>
#include <nt2/core/include/functions/simd/freqspace1.hpp>
#include <nt2/core/include/functions/simd/from_diag.hpp>
#include <nt2/core/include/functions/simd/function.hpp>
#include <nt2/core/include/functions/simd/function_index.hpp>
#include <nt2/core/include/functions/simd/global.hpp>
#include <nt2/core/include/functions/simd/globalall.hpp>
#include <nt2/core/include/functions/simd/globalany.hpp>
#include <nt2/core/include/functions/simd/globalasum1.hpp>
#include <nt2/core/include/functions/simd/globalasum2.hpp>
#include <nt2/core/include/functions/simd/globalasump.hpp>
#include <nt2/core/include/functions/simd/globalfind.hpp>
#include <nt2/core/include/functions/simd/globalmax.hpp>
#include <nt2/core/include/functions/simd/globalmean.hpp>
#include <nt2/core/include/functions/simd/globalmeanad.hpp>
#include <nt2/core/include/functions/simd/globalmedian.hpp>
#include <nt2/core/include/functions/simd/globalmedianad.hpp>
#include <nt2/core/include/functions/simd/globalmin.hpp>
#include <nt2/core/include/functions/simd/globalnone.hpp>
#include <nt2/core/include/functions/simd/globalnorm2.hpp>
#include <nt2/core/include/functions/simd/globalnormp.hpp>
#include <nt2/core/include/functions/simd/globalprod.hpp>
#include <nt2/core/include/functions/simd/globalstdev.hpp>
#include <nt2/core/include/functions/simd/globalsum.hpp>
#include <nt2/core/include/functions/simd/globalvar.hpp>
#include <nt2/core/include/functions/simd/gold.hpp>
#include <nt2/core/include/functions/simd/half.hpp>
#include <nt2/core/include/functions/simd/halfeps.hpp>
#include <nt2/core/include/functions/simd/havesamesize.hpp>
#include <nt2/core/include/functions/simd/height.hpp>
#include <nt2/core/include/functions/simd/homot.hpp>
#include <nt2/core/include/functions/simd/horzcat.hpp>
#include <nt2/core/include/functions/simd/hundred.hpp>
#include <nt2/core/include/functions/simd/idivide.hpp>
#include <nt2/core/include/functions/simd/ifvectvert.hpp>
#include <nt2/core/include/functions/simd/ind2ind.hpp>
#include <nt2/core/include/functions/simd/ind2sub.hpp>
#include <nt2/core/include/functions/simd/indices.hpp>
#include <nt2/core/include/functions/simd/inf.hpp>
#include <nt2/core/include/functions/simd/inner_fold.hpp>
#include <nt2/core/include/functions/simd/inner_scan.hpp>
#include <nt2/core/include/functions/simd/int_splat.hpp>
#include <nt2/core/include/functions/simd/iscolumn.hpp>
#include <nt2/core/include/functions/simd/isdiagonal.hpp>
#include <nt2/core/include/functions/simd/isempty.hpp>
#include <nt2/core/include/functions/simd/isequal.hpp>
#include <nt2/core/include/functions/simd/isequaln.hpp>
#include <nt2/core/include/functions/simd/isexpandable_to.hpp>
#include <nt2/core/include/functions/simd/isfloating.hpp>
#include <nt2/core/include/functions/simd/ishermitian.hpp>
#include <nt2/core/include/functions/simd/isinside.hpp>
#include <nt2/core/include/functions/simd/isinteger.hpp>
#include <nt2/core/include/functions/simd/ismatrix.hpp>
#include <nt2/core/include/functions/simd/isreal.hpp>
#include <nt2/core/include/functions/simd/isrow.hpp>
#include <nt2/core/include/functions/simd/isscalar.hpp>
#include <nt2/core/include/functions/simd/issorted.hpp>
#include <nt2/core/include/functions/simd/issquare.hpp>
#include <nt2/core/include/functions/simd/issymetric.hpp>
#include <nt2/core/include/functions/simd/istriangular.hpp>
#include <nt2/core/include/functions/simd/istril.hpp>
#include <nt2/core/include/functions/simd/istriu.hpp>
#include <nt2/core/include/functions/simd/isulpequal.hpp>
#include <nt2/core/include/functions/simd/isvector.hpp>
#include <nt2/core/include/functions/simd/isvectoralong.hpp>
#include <nt2/core/include/functions/simd/last_index.hpp>
#include <nt2/core/include/functions/simd/ldexpmask.hpp>
#include <nt2/core/include/functions/simd/length.hpp>
#include <nt2/core/include/functions/simd/line.hpp>
#include <nt2/core/include/functions/simd/linear_interp.hpp>
#include <nt2/core/include/functions/simd/linesstride.hpp>
#include <nt2/core/include/functions/simd/linspace.hpp>
#include <nt2/core/include/functions/simd/log10_pi.hpp>
#include <nt2/core/include/functions/simd/logspace.hpp>
#include <nt2/core/include/functions/simd/maxexponent.hpp>
#include <nt2/core/include/functions/simd/maxinit.hpp>
#include <nt2/core/include/functions/simd/maxleftshift.hpp>
#include <nt2/core/include/functions/simd/mean.hpp>
#include <nt2/core/include/functions/simd/meanad.hpp>
#include <nt2/core/include/functions/simd/median.hpp>
#include <nt2/core/include/functions/simd/medianad.hpp>
#include <nt2/core/include/functions/simd/meight.hpp>
#include <nt2/core/include/functions/simd/meshgrid.hpp>
#include <nt2/core/include/functions/simd/mfive.hpp>
#include <nt2/core/include/functions/simd/mfour.hpp>
#include <nt2/core/include/functions/simd/mhalf.hpp>
#include <nt2/core/include/functions/simd/mindenormal.hpp>
#include <nt2/core/include/functions/simd/minexponent.hpp>
#include <nt2/core/include/functions/simd/minf.hpp>
#include <nt2/core/include/functions/simd/mlogeps2.hpp>
#include <nt2/core/include/functions/simd/mnine.hpp>
#include <nt2/core/include/functions/simd/mone.hpp>
#include <nt2/core/include/functions/simd/moneo_6.hpp>
#include <nt2/core/include/functions/simd/mseven.hpp>
#include <nt2/core/include/functions/simd/msix.hpp>
#include <nt2/core/include/functions/simd/mten.hpp>
#include <nt2/core/include/functions/simd/mthree.hpp>
#include <nt2/core/include/functions/simd/mtwo.hpp>
#include <nt2/core/include/functions/simd/mzero.hpp>
#include <nt2/core/include/functions/simd/nan.hpp>
#include <nt2/core/include/functions/simd/nanasum2.hpp>
#include <nt2/core/include/functions/simd/nanmean.hpp>
#include <nt2/core/include/functions/simd/nansum.hpp>
#include <nt2/core/include/functions/simd/nbdigits.hpp>
#include <nt2/core/include/functions/simd/nbexponentbits.hpp>
#include <nt2/core/include/functions/simd/nblines.hpp>
#include <nt2/core/include/functions/simd/nbmantissabits.hpp>
#include <nt2/core/include/functions/simd/ndgrid.hpp>
#include <nt2/core/include/functions/simd/ndims.hpp>
#include <nt2/core/include/functions/simd/nine.hpp>
#include <nt2/core/include/functions/simd/norm2.hpp>
#include <nt2/core/include/functions/simd/normp.hpp>
#include <nt2/core/include/functions/simd/numel.hpp>
#include <nt2/core/include/functions/simd/of_size.hpp>
#include <nt2/core/include/functions/simd/ofsameheight.hpp>
#include <nt2/core/include/functions/simd/ofsamewidth.hpp>
#include <nt2/core/include/functions/simd/oneo_10.hpp>
#include <nt2/core/include/functions/simd/oneo_12.hpp>
#include <nt2/core/include/functions/simd/oneo_120.hpp>
#include <nt2/core/include/functions/simd/oneo_15.hpp>
#include <nt2/core/include/functions/simd/oneo_180.hpp>
#include <nt2/core/include/functions/simd/oneo_5.hpp>
#include <nt2/core/include/functions/simd/oneo_6.hpp>
#include <nt2/core/include/functions/simd/oneo_7.hpp>
#include <nt2/core/include/functions/simd/oneo_8.hpp>
#include <nt2/core/include/functions/simd/oneo_9.hpp>
#include <nt2/core/include/functions/simd/ones.hpp>
#include <nt2/core/include/functions/simd/outer_fold.hpp>
#include <nt2/core/include/functions/simd/outer_scan.hpp>
#include <nt2/core/include/functions/simd/pi.hpp>
#include <nt2/core/include/functions/simd/pio_2.hpp>
#include <nt2/core/include/functions/simd/pispace.hpp>
#include <nt2/core/include/functions/simd/putalong.hpp>
#include <nt2/core/include/functions/simd/quarter.hpp>
#include <nt2/core/include/functions/simd/rand.hpp>
#include <nt2/core/include/functions/simd/randi.hpp>
#include <nt2/core/include/functions/simd/randn.hpp>
#include <nt2/core/include/functions/simd/real_splat.hpp>
#include <nt2/core/include/functions/simd/relative_index.hpp>
#include <nt2/core/include/functions/simd/relative_size.hpp>
#include <nt2/core/include/functions/simd/rephorz.hpp>
#include <nt2/core/include/functions/simd/repmat.hpp>
#include <nt2/core/include/functions/simd/repnum.hpp>
#include <nt2/core/include/functions/simd/repvert.hpp>
#include <nt2/core/include/functions/simd/reshape.hpp>
#include <nt2/core/include/functions/simd/resize.hpp>
#include <nt2/core/include/functions/simd/ric.hpp>
#include <nt2/core/include/functions/simd/rif.hpp>
#include <nt2/core/include/functions/simd/rng.hpp>
#include <nt2/core/include/functions/simd/rows.hpp>
#include <nt2/core/include/functions/simd/rowvect.hpp>
#include <nt2/core/include/functions/simd/seven.hpp>
#include <nt2/core/include/functions/simd/signmask.hpp>
#include <nt2/core/include/functions/simd/six.hpp>
#include <nt2/core/include/functions/simd/size.hpp>
#include <nt2/core/include/functions/simd/smallestposval.hpp>
#include <nt2/core/include/functions/simd/splitfactor.hpp>
#include <nt2/core/include/functions/simd/sqrt_1o_5.hpp>
#include <nt2/core/include/functions/simd/sqrt_2.hpp>
#include <nt2/core/include/functions/simd/sqrt_2o_2.hpp>
#include <nt2/core/include/functions/simd/sqrt_2o_3.hpp>
#include <nt2/core/include/functions/simd/sqrteps.hpp>
#include <nt2/core/include/functions/simd/sqrtsmallestposval.hpp>
#include <nt2/core/include/functions/simd/sqrtvalmax.hpp>
#include <nt2/core/include/functions/simd/squeeze.hpp>
#include <nt2/core/include/functions/simd/stdev.hpp>
#include <nt2/core/include/functions/simd/sub2ind.hpp>
#include <nt2/core/include/functions/simd/sub2sub.hpp>
#include <nt2/core/include/functions/simd/sx.hpp>
#include <nt2/core/include/functions/simd/sxfun.hpp>
#include <nt2/core/include/functions/simd/ten.hpp>
#include <nt2/core/include/functions/simd/third.hpp>
#include <nt2/core/include/functions/simd/thirdrooteps.hpp>
#include <nt2/core/include/functions/simd/thousand.hpp>
#include <nt2/core/include/functions/simd/three.hpp>
#include <nt2/core/include/functions/simd/threeeps.hpp>
#include <nt2/core/include/functions/simd/tie.hpp>
#include <nt2/core/include/functions/simd/transform.hpp>
#include <nt2/core/include/functions/simd/transpose.hpp>
#include <nt2/core/include/functions/simd/trapz.hpp>
#include <nt2/core/include/functions/simd/tri1l.hpp>
#include <nt2/core/include/functions/simd/tri1u.hpp>
#include <nt2/core/include/functions/simd/tril.hpp>
#include <nt2/core/include/functions/simd/triu.hpp>
#include <nt2/core/include/functions/simd/trues.hpp>
#include <nt2/core/include/functions/simd/twelve.hpp>
#include <nt2/core/include/functions/simd/twenty.hpp>
#include <nt2/core/include/functions/simd/two.hpp>
#include <nt2/core/include/functions/simd/twoto31.hpp>
#include <nt2/core/include/functions/simd/twotom10.hpp>
#include <nt2/core/include/functions/simd/twotonmb.hpp>
#include <nt2/core/include/functions/simd/valmax.hpp>
#include <nt2/core/include/functions/simd/valmin.hpp>
#include <nt2/core/include/functions/simd/var.hpp>
#include <nt2/core/include/functions/simd/vertcat.hpp>
#include <nt2/core/include/functions/simd/whereij.hpp>
#include <nt2/core/include/functions/simd/width.hpp>
#include <nt2/core/include/functions/simd/wmean.hpp>
#include <nt2/core/include/functions/simd/zeros.hpp>

#endif
